name: Install and Deploy Profile App

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Git Configs
        run: |
          git config --global user.email "ahummel25@gmail.com"
          git config --global user.name "Andrew Hummel"
          git remote set-url origin git@github.com:ahummel25/profile.git

      - name: Setup SSH Keys
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          check-latest: true

      - name: Cache NPM dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-npm-cache-

      - name: NPM Install
        run: npm install --force

      - name: NPM Test
        run: npm test

      - name: NPM Deploy
        env:
          GATSBY_GOOGLE_ANALYTICS_ID: ${{ secrets.GOOGLE_ANALYTICS_ID }}
          GATSBY_WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
        run: |
          echo Deploying as "$GITHUB_ACTOR" in repo "$GITHUB_REPOSITORY"
          npm run deploy
