name: Install and Deploy Profile App

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.2

      - name: Setup Git Configs
        run: |
          git config --global user.email "ahummel25@gmail.com"
          git config --global user.name "Andrew Hummel"
          git remote set-url origin git@github.com:ahummel25/profile.git

      - name: Setup SSH Keys
        uses: webfactory/ssh-agent@v0.4.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: NPM Install
        run: npm install

      - name: NPM Test
        run: npm test

      - name: NPM Deploy
        env:
          GATSBY_WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
        run: |
          echo Deploying as "$GITHUB_ACTOR" in repo "$GITHUB_REPOSITORY"
          npm run deploy
