name: Install and Deploy Profile App

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          check-latest: true

      - name: NPM Install
        run: npm install

      - name: NPM Test
        run: npm test

      - name: NPM Deploy
        env:
          GATSBY_GOOGLE_ANALYTICS_ID: ${{ secrets.GOOGLE_ANALYTICS_ID }}
          GATSBY_WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
        run: |
          echo Deploying as "$GITHUB_ACTOR" in repo "$GITHUB_REPOSITORY"
          npm run deploy
