name: Install and Deploy Profile

on:
  push:
    branches:
      - initial-branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Setup Git Configs
        run: |
          git config --global user.email "ahummel25@gmail.com"
          git config --global user.name "Andrew Hummel"
          git remote set-url origin https://ahummel25:$GITHUB_TOKEN@github.com/profile
      - name: Yarn install and deploy
        run: |
          yarn install
          yarn deploy
        env:
          GATSBY_ENV_TEST: ${{ secrets.GATSBY_ENV_TEST }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
