name: Inject Environment Variables

on:
  push:
    branches:
      - initial-branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install
      - run: yarn

      - uses: actions/checkout@v2
      - name: Deploy
        run: yarn deploy
        env:
          GATSBY_ENV_TEST: ${{ secrets.GATSBY_ENV_TEST }}
