name: Install and Deploy Profile

on:
  push:
    branches:
      - initial-branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
      - name: Setup Git Configs
        run: |
          git config --global user.email "ahummel25@gmail.com"
          git config --global user.name "Andrew Hummel"
      - name: Setup SSH Keys and known_hosts
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.SSH_SECRET_KEY }}"
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Yarn install and deploy
        env:
          GATSBY_ENV_TEST: ${{ secrets.GATSBY_ENV_TEST }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          yarn install
          yarn deploy
