name: Install and Deploy Profile

on:
  push:
    branches:
      - initial-branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Git Configs
        run: |
          git config --global user.email "ahummel25@gmail.com"
          git config --global user.name "Andrew Hummel"
      - name: Setup SSH Keys
        uses: webfactory/ssh-agent@v0.2.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Yarn install and deploy
        env:
          GATSBY_ENV_TEST: ${{ secrets.GATSBY_ENV_TEST }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          yarn install
          yarn deploy
