name: Inject Environment Variables

on: push

jobs:
  update:
    steps:
      - uses: actions/checkout@gh-pages
      - name: Deploy
        run: yarn deploy
        env:
          GATSBY_ENV_TEST: ${{ secrets.GATSBY_ENV_TEST }}
